import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    unit: "pair",
    name: "candles1",
    provider: "ABC company",
    price: `US$${1234.12}`,
    minOrder: `${10} pieces`,
    country: "USA",
    category: "Candles",
    images: {
      image1: "/images/candles/candle1/image1.webp",
      image2: "/images/candles/candle2/image2.webp",
      image3: "/images/candles/candle1/image3.jpeg",
      image4: "/images/candles/candle1/image4.jpeg",
      image5: "/images/candles/candle1/image5.webp",
    },
    attributes: {
      attribute1: "Attribute1",
      attribute2: "Attribute2",
      attribute3: "Attribute3",
      attribute4: "Attribute4",
      attribute5: "Attribute5",
      attribute6: "Attribute6",
      attribute7: "Attribute7",
      attribute8: "Attribute8",
      attribute9: "Attribute9",
      attribute10: "Attribute10",
    },
    leadTime: {
      "1-100": 15,
      "101-600": 30,
      "> 600": "to be negotiated",
    },
    sample: {
      max: 1,
      price: 20,
    },
  },
  {
    id: 2,
    unit: "pair",
    name: "candles2",
    provider: "DEF company",
    price: `US$${1234.12}`,
    minOrder: `${10} pieces`,
    country: "USA",
    category: "Candles",
    images: {
      image1: "/images/candles/candle2/image1.jpeg",
      image2: "/images/candles/candle2/image2.webp",
      image3: "/images/candles/candle2/image3.jpeg",
      image4: "/images/candles/candle2/image4.webp",
      image5: "/images/candles/candle2/image5.webp",
    },
    attributes: {
      attribute1: "Attribute1",
      attribute2: "Attribute2",
      attribute3: "Attribute3",
      attribute4: "Attribute4",
      attribute5: "Attribute5",
    },
    leadTime: {
      "1-100": 15,
      "101-600": 30,
      "> 600": "to be negotiated",
    },
    sample: {
      max: 1,
      price: 20,
    },
  },
  {
    id: 3,
    name: "candles3",
    unit: "pair",
    provider: "GHI company",
    price: `US$${1234.12}`,
    minOrder: `${10} pieces`,
    country: "USA",
    category: "Candles",
    images: {
      image1: "/images/candles/candle3/image1.webp",
      image2: "/images/candles/candle3/image2.webp",
      image3: "/images/candles/candle3/image3.jpeg",
      image4: "/images/candles/candle3/image4.jpeg",
      image5: "/images/candles/candle3/image1.webp",
    },
    attributes: {
      attribute1: "Attribute1",
      attribute2: "Attribute2",
      attribute3: "Attribute3",
      attribute4: "Attribute4",
      attribute5: "Attribute5",
    },
    leadTime: {
      "1 - 100": 15,
      "101 - 600": 30,
      "> 600": "to be negotiated",
    },
    sample: {
      max: 1,
      price: 20,
    },
  },
  {
    id: 4,
    name: "candles4",
    unit: "pair",
    provider: "KLM company",
    price: `US$${1234.12}`,
    minOrder: `${10} pieces`,
    country: "USA",
    category: "Candles",
    images: {
      image1: "/images/candles/candle4/image1.webp",
      image2: "/images/candles/candle4/image2.jpeg",
      image3: "/images/candles/candle4/image3.jpeg",
      image4: "/images/candles/candle4/image4.jpeg",
      image5: "/images/candles/candle4/image5.webp",
    },
    attributes: {
      attribute1: "Attribute1",
      attribute2: "Attribute2",
      attribute3: "Attribute3",
      attribute4: "Attribute4",
      attribute5: "Attribute5",
    },
    leadTime: {
      "1-100": 15,
      "101-600": 30,
      "> 600": "to be negotiated",
    },
    sample: {
      max: 1,
      price: 20,
    },
  },
  {
    id: 5,
    name: "candles5",
    unit: "pair",
    provider: "XYZ company",
    price: `US$${1234.12}`,
    minOrder: `${10} pieces`,
    country: "USA",
    category: "Candles",
    images: {
      image1: "/images/candles/candle5/image1.webp",
      image2: "/images/candles/candle5/image2.webp",
      image3: "/images/candles/candle5/image3.jpeg",
      image4: "/images/candles/candle5/image4.avif",
      image5: "/images/candles/candle5/image5.jpeg",
    },
    attributes: {
      attribute1: "Attribute1",
      attribute2: "Attribute2",
      attribute3: "Attribute3",
      attribute4: "Attribute4",
      attribute5: "Attribute5",
    },
    leadTime: {
      "1-100": 15,
      "101-600": 30,
      "> 600": "to be negotiated",
    },
    sample: {
      max: 1,
      price: 20,
    },
  },
];
